### ISSUE TITLE
Getting 422 Signature Verification Failed error

### ISSUE THREAD

**Issue by s-a-c-h-i-n** [YashMarmat/Instagram-clone-with-FLASK#2]
![image](https://github.com/YashMarmat/Instagram-clone-with-FLASK/assets/30471507/a4e14b99-4ec8-4e13-a8ba-02fa276e4e8f)

![image](https://github.com/YashMarmat/Instagram-clone-with-FLASK/assets/30471507/bbe6fc0a-e60e-41cd-8b96-a17d16eea579)

**Comment by YashMarmat** [comment]
Hi @s-a-c-h-i-n seems like the token you are using is invalid or expired. Please use the login API to generate a new access token and use that one.

**Comment by YashMarmat** [comment]
I hope this helps, closing this issue, please create a new one for further queries or issues.
